config/routes.rb
Rails.application.routes.draw do

resources :books
root to: 'homes#index'
get "books" => 'books#index'
post 'books' => 'books#create'
post 'books/:id' => 'books#create'
get 'books/:id' => 'books#show',    as: "books_show"
get 'books/:id/edit' => 'books#edit', as: "books_edit"
patch 'books/:id' => 'books#update', as: 'update_book'
put 'books/:id' => 'books#update'
delete 'books/:id'  => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new

  end

  def show
    @book = Book.new
    @book = Book.find(params[:id])

  end

  def new
  end

def create
 @book = Book.new(book_params)
if  @book.save
    redirect_to books_show_path(@book), notice:  "successfully"
else
  @books = Book.all
  render  :index

end

end

  def edit
  @book = Book.find(params[:id])
  end

  def update
  @book = Book.find(params[:id])
  if  @book.update(book_params)
   redirect_to books_show_path(@book), notice:  "successfully"
  else
    render :edit
  end
  end

def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to '/books'
end

private

def book_params
     params.require(:book).permit(:title,  :body)
end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
def books
  
end
  def show
    end
end

app/controllers/todolist_controller.rb
class TodolistController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolist_helper.rb
module TodolistHelper
end

app/views/books/_form.html.erb
<h1>New book</h1>
<%= form_for @book,  do |f| %>

<h4>Title</h4>
<%= f.label(:title, title)
<%= f.text_area :title %>

<h4>Body</h4>
<%= f.label(:body, body)
<%= f.text_area :body %>
<br>

<%= f.submit 'Create Book' %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<div id = "error_explanation" >
 <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <br>
 <ul> <% @book.errors.full_messages.each do |message| %>
   <li> <%= message %> </li>
  <% end %>
<ul>  </div>
<% end %>

<h1>Editing Bookt</h1>
<%= form_with model:@book,   local: true do |f| %>
<p>title</p>
<%= f.text_field :title %>
<p>body</p>
<%= f.text_area :body %><br>
<%= f.submit 'Update Book' %>
<% end %>

<tr><%= link_to "Show", book_path  %>

    |

<%= link_to "Back", "/books" %>

</tr>

app/views/books/index.html.erb
<%= flash[:notice] %>
<h1>Books</h1>

<table  width="737">
    <tr>
      <th width="192" >Title</th>
      <th width="400" >Body</th>
      <th width="145"></th>
    </tr>
<tbody>
  <% @books.each do |book| %>
<tr>
<th  width="192"><%= book.title %></th>
<th  width="400"><%= book.body %></th>

<th><%= link_to "Show", book_path(book.id) %>
<%= link_to "Edit", "/books/#{book.id}/edit" %>
<%= link_to "Destroy", "/books/#{book.id}", method: :delete,
"data-confirm" => "Are you sure?" %></th>
</tr>
<% end %>
</tbody>

</table>



<h1>New book</h1>

<% if @book.errors.any? %>
<div id = "error_explanation" >
 <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <br>
 <ul> <% @book.errors.full_messages.each do |message| %>
   <li> <%= message %> </li>
  <% end %>
<ul>  </div>
<% end %>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_area :title %>

<h4>Body</h4>
<%= f.text_area :body %>
<br>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>



<h1>New book</h1>
<%= form_with model:@book, local:true do |f| %>


<h4>Title</h4>
<%= f.text_area :title %>

<h4>Body</h4>
<%= f.text_area :body %>
<br>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>

<p>Title:<%= @book.title %></p>
<p>Body: <%= @book.body %> </p>

<tr><%= link_to "Edit", books_edit_path  %>

    |

<%= link_to "Back", "/books" %>

</tr>

app/views/homes/index.html.erb
<h1>ようこそ
<storong>Bookers</storong>
へ！</h1>
<p><storong>Bookers</storong>では、さまざまな書籍に関するあなたの意見や<br>
<br><br>
印象を共有し交換することができます
</p>
<p>
<%= link_to "start", "/books" %>
</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolist/new.html.erb
<h1>Todolist#new</h1>
<p>Find me in app/views/todolist/new.html.erb</p>